apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: kongroo-notifications:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-config
            - secretRef:
                name: notifications-secret
