apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kongroo

resources:
  - namespace.yaml
  - aws-credentials.secret.yaml
  - postgres/configmap.yaml
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - rabbitmq/configmap.yaml
  - rabbitmq/secret.yaml
  - rabbitmq/pvc.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - kong/deployment.yaml
  - kong/service.yaml
  - kong/status-service.yaml
  - mongodb/secret.yaml
  - mongodb/pvc.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - grafana/secret.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - identity
  - catalog
  - payments

secretGenerator:
  - name: kong-declarative
    files:
      - kong/kong.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yml
  - name: grafana-datasources
    files:
      - grafana/provisioning/datasources/datasource.yaml
  - name: grafana-dashboard-providers
    files:
      - grafana/provisioning/dashboards/dashboards.yaml
  - name: grafana-dashboards
    files:
      - grafana/dashboards/kongroo.json

images:
  - name: josealmeidajr/kongroo-identity
    newTag: "0.1.0"
  - name: josealmeidajr/kongroo-catalog
    newTag: "0.1.0"
  - name: josealmeidajr/kongroo-payments
    newTag: "0.1.0"
