apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kongroo

resources:
  - namespace.yaml
  - postgres/configmap.yaml
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - rabbitmq/configmap.yaml
  - rabbitmq/secret.yaml
  - rabbitmq/pvc.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - identity
  - catalog
  - payments
  - notifications

images:
  - name: josealmeidajr/kongroo-identity
    newTag: "0.0.6"
  - name: kongroo-catalog
    newName: josealmeidajr/kongroo-catalog
    newTag: "0.0.5"
  - name: kongroo-payments
    newName: josealmeidajr/kongroo-payments
    newTag: "0.0.4"
  - name: kongroo-notifications
    newName: josealmeidajr/kongroo-notifications
    newTag: "0.0.4"
