apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
        - name: identity-api
          image: josealmeidajr/kongroo-identity:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: identity-config
            - secretRef:
                name: identity-secret
