apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  ConnectionStrings__Database: "Host=postgres;Database=kongroo_identity;Username=kongroo;Password=development"
  Jwt__SigningKey: "Development.SigningKey.AtLeast32Characters!"
  BootstrapAdmin__Password: "Sup3rSecure!"
  RabbitMq__User: "kongroo"
  RabbitMq__Pass: "development"
